### ISSUE TITLE
Firmware doesn't compile on Windows with multiple_sheets merged.

### ISSUE THREAD

**Issue by leptun** [prusa3d/Prusa-Firmware#1965]
As the title says, it errors while compiling because of something related to eeprom.
Compiled on the MK3 branch with no modifications.

`C:\GIt\Prusa-Firmware\Prusa-Firmware-build\sketch\eeprom.h:221:1: error: non-constant condition for static assertion`
` static_assert(((sizeof(M500_conf) + 20) < EEPROM_LAST_ITEM), "M500_conf address space conflicts with previous items.");`

**Comment by leptun** [comment]
Also at line 191 in eeprom.h shouldn't `EEPROM_NOZZLE_DIAMETER `be `EEPROM_NOZZLE_DIAMETER_uM `?

**Comment by maximlevitsky** [comment]
Appears to compile here (linux, with build.sh script).

Note though that there is currently a cosmetic issue if you compile with language support - the multiple sheet selection menu has 2 letters missing from each menu - this is due the fact that the strings are passed to the translation function (_T()) but are not added to the translation. They will fix that for sure I think. Other than that it works superb.

**Comment by leptun** [comment]
I am using PF-build.sh script. I am attempting to build on windows 10 with git bash. Did not enable multiple languages as I don't need them :)

**Comment by vertigo235** [comment]
I built it fine, also included your LCD fix @leptun

**Comment by vertigo235** [comment]
I also can confirm the issue of truncated menu items that @maximlevitsky reported, but so far the multi sheets seem to work I have calibrated 2 sheets already.

**Comment by leptun** [comment]
Just tested on linux subsystem for windows with build.sh and PF-build.sh and it compiled on both of them. I suppose there is some difference between the linux and the windows variants of gcc.

**Comment by leptun** [comment]
On windows the firmware compiles only with #1963 or #1934, but not both. It fails on the compile time checks added in #1934.

**Comment by mkbel** [comment]
> Also at line 191 in eeprom.h shouldn't `EEPROM_NOZZLE_DIAMETER `be `EEPROM_NOZZLE_DIAMETER_uM `?

Fixed in https://github.com/prusa3d/Prusa-Firmware/pull/1982

**Comment by mkbel** [comment]
> Appears to compile here (linux, with build.sh script).
> 
> Note though that there is currently a cosmetic issue if you compile with language support - the multiple sheet selection menu has 2 letters missing from each menu - this is due the fact that the strings are passed to the translation function (_T()) but are not added to the translation. They will fix that for sure I think. Other than that it works superb.

Fixed in https://github.com/prusa3d/Prusa-Firmware/pull/1980

**Comment by mkbel** [comment]
> As the title says, it errors while compiling because of something related to eeprom.
> Compiled on the MK3 branch with no modifications.
> 
> `C:\GIt\Prusa-Firmware\Prusa-Firmware-build\sketch\eeprom.h:221:1: error: non-constant condition for static assertion`
> ` static_assert(((sizeof(M500_conf) + 20) < EEPROM_LAST_ITEM), "M500_conf address space conflicts with previous items.");`

Fixed in https://github.com/prusa3d/Prusa-Firmware/pull/1984

**Comment by mkbel** [comment]
But anyway, Windows build is still expected to be broken by https://github.com/prusa3d/Prusa-Firmware/pull/1979 as this changed board definition. Our board definition is still work in progress as there is custom linker script missing and application size check fix missing https://github.com/DRracer/Arduino_Boards

**Comment by leptun** [comment]
@mkbel Ouf... Back to LSFW then :'(
