### PR TITLE
Fix compiler warning arduino-1.6.9/hardware/tools/avr/avr/include/avr…

### PR DESCRIPTION
**Pull request by mkbel**
…/delay.h:36:2: warning: #warning "This file has been moved to <util/delay.h>." [-Wcpp]

### CODE REVIEW

**Comment by 3d-gussner** [comment]
@mkbel I thought we have to use Arduino IDE 1.6.8 and not upgrade AVR boards to compile the firmware? I have successfully compiled MK2 and MK3 branches with IDE 1.8.x and saved a lot of space using the newest versions. To apply to Prusa standards I installed portable 1.6.8 version and don't update AVR boards but don't see any different behavior of my MK2 using IDE 1.8.x or the old 1.6.8 version. Or is it a typo 1.6.9?

**Comment by mkbel** [comment]
@3d-gussner Thank you for your note. We are using 1.6.9 on build server now, I will update this in build instructions. We would be happy to use later compiler, but we are unable to use Arduino 1.8.x, as we encounter compiler bug
e.g.:
sketch/Marlin_main.cpp:3044:1: internal compiler error: in extract_insn, at recog.c:2202

**Comment by Zaf9670** [comment]
I just tried to compile on 1.8.10 Windows Store edition and got the following for reference.

Arduino: 1.8.5 (Windows Store 1.8.10.0) (Windows 10), Board: "RAMBo"

Archiving built core (caching) in: C:\Users\xxxx\AppData\Local\Temp\arduino_cache_887645\core\core_rambo_avr_rambo_a94ab6aaf61dfb93b4a8079c694a14c2.a
sketch\Marlin_main.cpp: In function 'gcode_M45.constprop':

Marlin_main.cpp:3044: error: unrecognizable insn:

 }

 ^

(insn 792 791 793 28 (set (reg:QI 1009)

        (subreg:QI (mem/v/c:SI (plus:HI (reg/f:HI 1008)

                    (const_int 8 [0x8])) [6 count_position+8 S4 A8]) 3)) sketch\xyzcal.cpp:773 -1

     (nil))

sketch\Marlin_main.cpp:3044:1: internal compiler error: in extract_insn, at recog.c:2202

**Comment by 3d-gussner** [comment]
There are several issue reports and pull request for that like
https://github.com/prusa3d/Prusa-Firmware/pull/817/files
https://github.com/prusa3d/Prusa-Firmware/pull/620
https://github.com/prusa3d/Prusa-Firmware/pull/767 read my and @XPila his comments
