### PR TITLE
Remove build warnings (all) - fix some spelling errors

### PR DESCRIPTION
**Pull request by thess**
Want a clean build? Give these changes a go.
I have printed several items with this version and have not seen any (new) problems. 

Some of the format changes introduced were done to improve readability and
remove compiler warnings about needing parenthesis. Some code restructuring has been done to eliminate unused code and variables. Also cleaned-up several defined but unused functions.

There were a couple of ambiguous items in planner.cpp (calculation of bresenham over-sample) and in stepper.cpp (pulse timing) I think are handled correctly now.

Looking forward to feedback and/or fixing any errors inadvertently introduced. 

Updated on 5-Oct-2017 to reflect firmware v3.1.0-RC1.

### CODE REVIEW

**Comment by thess** [comment]
I've updated this PR to apply cleanly to the last version (3.0.12-5). Perhaps we should do this and cleanup the builds. Do you need any help or further clarifications?

**Comment by thess** [comment]
Once again, updated to latest (3.1.0-RC1).
@PavelSindler, et.al. -- If you really don't want to cleanup your sources (or maybe just not care), I'll stop doing these updates and just keep them in my private repo which produces clean builds and is easier to work on.

**Comment by JohnOCFII** [comment]
It would be great if Prusa Research would accept this PR, or otherwise ease the build process.

**Comment by thess** [comment]
Yes, it would... and nice if they would stop declaring functions 'static' in header files included by multiple sources - sigh... They should be building with full warnings enabled and addressed before releasing firmware

**Comment by ryanneufeld** [comment]
````
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/Marlin_main.cpp: In function 'void gcode_M701()':
Marlin_main.cpp:2148: error: 'extr_adj' was not declared in this scope
  extr_adj(snmm_extruder);//loads current extruder
                        ^
exit status 1
'extr_adj' was not declared in this scope
````

I get that error when using the variants/1_75mm_MK2-MultiMaterial-RAMBo13a-E3Dv6full.h config on your branch @thess 



I will also add that it would be nice for Prusa to share how they build this, in a comprehensive way.

**Comment by thess** [comment]
Whoops - I thought I had tested SNMM variant.
Thanks for trying this, now fixed.

**Comment by ryanneufeld** [comment]
no dice
````
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/Marlin_main.cpp.o: In function `gcode_M701()':
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/Marlin_main.cpp:2148: undefined reference to `snmm_extruder'
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/Marlin_main.cpp:2148: undefined reference to `extr_adj(int)'
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/Marlin_main.cpp.o: In function `process_commands()':
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/Marlin_main.cpp:5439: undefined reference to `snmm_extruder'
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/Marlin_main.cpp:5499: undefined reference to `display_loading()'
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/Marlin_main.cpp:5509: undefined reference to `snmm_extruder'
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/Marlin_main.cpp:5588: undefined reference to `display_loading()'
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/Marlin_main.cpp:5562: undefined reference to `snmm_extruder'
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/Marlin_main.cpp:5721: undefined reference to `extr_unload_used()'
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/Marlin_main.cpp:5730: undefined reference to `extr_unload()'
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/Marlin_main.cpp:5731: undefined reference to `extr_unload_all()'
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/Marlin_main.cpp:5779: undefined reference to `snmm_extruder'
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/Marlin_main.cpp:5779: undefined reference to `snmm_extruder'
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/stepper.cpp.o: In function `isr()':
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/stepper.cpp:548: undefined reference to `snmm_extruder'
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/stepper.cpp.o: In function `advance_isr()':
/var/folders/yx/wk0ymdbd55z77ffcw2k0y_2nvqk83t/T/build2c53ed1388fa3557601dbe8d6a0e4c56.tmp/sketch/stepper.cpp:743: undefined reference to `snmm_extruder'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board RAMBo.
````

**Comment by jtktam** [comment]
@thess is there a way to reach you for some help on related matters? thanks

**Comment by thess** [comment]
@ryanneufeld - I think you have a configuration problem now. Check to make sure your versions of `ultralcd.h` and `ultralcd.cpp` are in sync and try a **clean** build. There should not be any errors unless you have an unusual combination of configuration options which are un-tested by me.

Perhaps our build environments are significantly different - I have no problems with either Arduino 1.6.13 or platformio. Edit: clean build with Arduino 1.8.4 also.

**Comment by thess** [comment]
@jtktam - Post your issue here or start a new thread. I am generally not available for private (free) consulting.

**Comment by jtktam** [comment]
@thess not free, looking for somebody to help with a project

**Comment by ryanneufeld** [comment]
@thess I'm using 1.6.8 (as recommended somewhere I can't find now) and I am using your branch exactly.

Edit, just setup the 1.6.13 and it seems to compile okay now.

**Comment by thess** [comment]
Updated PR based on review feedback from @3d-gussner and @macfly1202 in #224.
To those trying to build the latest sources -- I would recommend using a more recent version of Arduino than the old 1.6.8 release - Use either a more recent 1.6.x or the latest 1.8.x.

**Comment by PavelSindler** [comment]
Hello @thess,
thank you for all the work you have done on this PR. I went through all the changes you did and it is really great improvement. When I compiled it with single material configuration file and let Arduino IDE use previously compiled files, there are no warnings. I am using arduino 1.8.3. If I remove all *.o files before compiling to rebuild all (or change board to force rebuild), there are still some warnings remaining. But it is now easier to check these warnings and fix it. Once again, thank you very much. I am merging it.

**Comment by thess** [comment]
Wow - thanks! I hope it will be easier now going forward.
