### ISSUE TITLE
Bang-Bang mode for heated bed not compiling

### ISSUE THREAD

**Issue by RetireeJay46** [prusa3d/Prusa-Firmware#814]
In Configuration.h, we have the following lines:
// Comment the following line to disable PID and enable bang-bang.
//#define PIDTEMP

This worked in 3.1.0, but does not work now.  Arduino reports this error:
`ConfigurationStore.cpp:224: error: 'unscalePID_i' was not declared in this scope

  SERIAL_ECHOPAIR(" I", unscalePID_i(bedKi));
`

**Comment by RetireeJay46** [comment]
Actually, the problem turns out to be the instructions in Configuration.h which are misleading.
Another instruction in Configuration_Prusa.h is correct.
`// Bed Temperature Control
// Select PID or bang-bang with PIDTEMPBED. If bang-bang, BED_LIMIT_SWITCHING will enable hysteresis
//
// Uncomment this to enable PID on the bed. It uses the same frequency PWM as the extruder.
// If your PID_dT above is the default, and correct for your hardware/configuration, that means 7.689Hz,
// which is fine for driving a square wave into a resistive load and does not significantly impact you FET heating.
// This also works fine on a Fotek SSR-10DA Solid State Relay into a 250W heater.
// If your configuration is significantly different than this and you don't understand the issues involved, you probably
// shouldn't use bed PID until someone else verifies your hardware works.
// If this is enabled, find your own PID constants below.
//#define PIDTEMPBED
//`
